defaults:
  - model: lcnn
  - writer: wandb
  - metrics: example
  - datasets: asvspoof
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}

loss_function:
  _target_: src.loss.ExampleLoss

trainer:
  log_step: 1
  n_epochs: 1
  epoch_len: null
  val_epoch_len: null
  device_tensors: ["audio", "audio_length", "labels"]
  resume_from: null
  device: auto
  override: True
  monitor: "min val_loss"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
