defaults:
  - model: lcnn
  - metrics: example
  - datasets: asvspoof_eval
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_

inferencer:
  device_tensors: ["audio", "audio_length", "labels"]
  device: auto
  save_path: "asvspoof_eval"
  seed: 1
  from_pretrained: "saved/model_best.pth"
