instance_transforms:
  train: null
  inference: null

batch_transforms:
  train:
    audio:
      _target_: src.transforms.STFTTransform
      n_fft: 512
      hop_length: 160
      win_length: 320
      max_frames: 600

  inference:
    audio:
      _target_: src.transforms.STFTTransform
      n_fft: 512
      hop_length: 160
      win_length: 320
      max_frames: 600
